name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^3.0.1
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  intl: ^0.17.0
  flutter_rounded_progress_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: Kalam Bold
    fonts:
    - asset: fonts/Kalam-Bold.ttf
      weight: 900
  - family: Kalam Light
    fonts:
    - asset: fonts/Kalam-Light.ttf
      weight: 300
  - family: Kalam Regular
    fonts:
    - asset: fonts/Kalam-Regular.ttf
      weight: 400
  - family: Lobster Regular
    fonts:
    - asset: fonts/Lobster-Regular.ttf
      weight: 400